<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <Deterministic>true</Deterministic>
    <VersionPrefix>0.1.0</VersionPrefix>
    <Authors>BadLiveware</Authors>
    <Company>BadLiveware</Company>
    <PackageProjectUrl>https://github.com/BadLiveware/LimitingFactor</PackageProjectUrl>
    <RepositoryUrl>https://github.com/BadLiveware/LimitingFactor.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>linux;sandbox;process;isolation;fuse;overlayfs</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
  </PropertyGroup>
</Project>
